# Test Cases
- repeated string: string1 = AAAA, string2 = A
- same string: string1 = ACTG, string2 = ACTG
- edge string on string1: string1 = ACTG string2 =TGCA
- edge string on string2: string1 = TGCA string2 = ACTG
- complete overlap on string1: string1 = AATTCGGG string2 = TT
- complete overlap on string2: string1 = TT string2 = AATTCGGG
- string1 is before string2: string1 = TTA string2: TTAGGC
- string2 is before string1: string1 = TTAGGC string2 = TTA
- multiple substrings: string1 = AACTGGC string2 = GGCAACT
- string1 = ATTG string2 = TTA
- string1 = ATTG string2 = TTAT
- string1 = AATCG string2 = GTTCG
- string1 = ACTG string2 = TGAC
- no overlap: string1 = ATT string2 = CCT


# Cases
1. Complete overlap for either string
2. The string is before the other string
3. The string is at the end of the other string
4. The matching substring HAS to be at the opposite end if they're both at ends


# Cases that should not be run (and can be checked initially)
1. The string completely matches each other
2. There is no match at all
