# Prime Pantry V2
Given a dictionary of items and their (integer, positive-valued) item weights, identify whether or not there is a subset that could fill a Prime Pantry Box to exactly 100% and report which items are in the subset.

## How to Run:
Run python program "primePantry.py" with command "python" in terminal (note: we are using python 3.6.3) with dictionary, number of items and total as command line arguments.

For example: python primePantry.py() "{'pepsi':55,'detergent':30, 'chips':25, 'cereal':15}" 4 100

Note: The dictionary is incased in double quotes, and each key in the dictionary is incased in single quotes.

## Python Version
Python 3.6.3

## Efficiency
This project is as efficient as a dynamic programming solution since the solution we implemented is dynamic programming. Our program implements dynamic programming by building on previous knowledge - we list all the sums between 0 and total (for example, from 0 to 4 we have the sums 0, 1, 2, 3, 4), and try to find a subset for each sum (i.e. 4 has a subset of 3 and 1) until we find a sum for x (or reach the end of the list of items). Finding a sum depends on previous sums (this is where previous knowledge is utilized). Once a match is found or we've reached the end of the list of items, the search ends. This is efficient when there are more than one possibly ways to get to a number, as it will immediately end the search after finding one output. By using this algorithm, the program is also more efficient than enumerating all possible subsets.

## Bonus point description
For our program, we implemented the bonus point in which "if there is no solution, returns the closest-without-going-over solution".
* If there is a solution less than the total inputted, the program will return the next largest solution.
* If there is no solution less than the total inputted, the program will print a line stating "Unfortunately, there are no items for you ..."

## Notes about program
* The program will not allow an item with weights less than or equal to zero.
* The program will return at least one list of items that fills the box to the indicated total amount.

## Project Collaborators:
Tiffany Xiao, Karen Santamaria

### Other:
The project can be found on [Github](https://github.com/tiffanyxiao/csc220-codingchallenges/blob/master/Coding%20Challenge%203/primePantry.py).
